services:

  postgres:
    image: postgres:17
    container_name: fittracker-db
    environment:
      POSTGRES_DB: fittracker
      POSTGRES_USER: fittracker
      POSTGRES_PASSWORD: fittracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Uncomment when React frontend is ready
  # frontend:
  #   build: ./frontend
  #   container_name: fittracker-ui
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
